# Generated by Django 4.1 on 2022-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='vivek_rules', max_length=55),
            preserve_default=False,
        ),
    ]
